### ISSUE TITLE
privatize all keys

### ISSUE THREAD

**Issue by nakaz** [andimiya/Buoy-Call#57]
https://github.com/andimiya/Final-Project/blob/development/server/server.js#L12

test or no test, always want to secure keys or any sort of potential sensitive stuff

**Comment by senakamura** [comment]
Not sure about this guy too https://github.com/andimiya/Final-Project/blob/development/client/src/components/StripeCheckout.js#L24

**Comment by andimiya** [comment]
Closed by PR's #58 #59 #60
